version: '3.8'

services:
  db:
    image: postgres:15
    container_name: volunteermanager_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: volunteer_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: volunteer_manager_development
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
