version: '3.8'

services:
  db:
    image: postgres:15
    container_name: volunteermanager_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: volunteer_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: volunteer_manager_development
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U volunteer_user"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      args:
        RAILS_ENV: development        # build with dev gems
        BUNDLE_WITHOUT: "test"
    container_name: volunteermanager_web
    command: bash -lc "bundle exec rails db:prepare && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      DATABASE_URL: postgres://volunteer_user:secure_password@db:5432/volunteer_manager_development

volumes:
  db_data:
