version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: volunteer_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: volunteer_manager_development
    ports:
      - "5432:5432"   # so you can also psql from host if you want
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: volunteermanager:prod           # built from the Dockerfile above
    depends_on: [db]
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      RAILS_SERVE_STATIC_FILES: "1"
      RAILS_LOG_TO_STDOUT: "1"
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}"
      DATABASE_URL: "postgres://volunteer_user:secure_password@db:5432/volunteer_manager_development"
    ports:
      - "3000:3000"

volumes:
  pgdata:
