default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: chris
  # explicitly use the Postgres socket—no TCP, no password
  host: "/var/run/postgresql"

development:
  <<: *default
  database: volunteer_manager_development

test:
  <<: *default
  database: volunteer_manager_test
