default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL", 5) %>

development:
  <<: *default
  database: volunteer_manager_development
  host: localhost
  port: 5432
  username: volunteer_user
  password: secure_password

# ✅ add this:
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  # If you ever use Supabase *pooled* URL (PgBouncer, often port 6543), also set:
  # prepared_statements: false
