default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  # ⚠️ If you ever switch to the pooled (PgBouncer, port 6543) URL:
  # prepared_statements: false
