default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USER", "volunteer_user") %>
  password: <%= ENV.fetch("DB_PASSWORD", "secure_password") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEV", "volunteer_manager_development") %>
