default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL", 5) %>

development:
  <<: *default
  url: postgres://volunteer_user:secure_password@localhost:5432/volunteer_manager_development

test:
  <<: *default
  url: postgres://volunteer_user:secure_password@localhost:5432/volunteer_manager_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  # If you ever use Supabase pooled (6543):
  # prepared_statements: false


default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL", 5) %>

development:
  <<: *default
  url: postgres://volunteer_user:secure_password@localhost:5432/volunteer_manager_development

test:
  <<: *default
  url: postgres://volunteer_user:secure_password@localhost:5432/volunteer_manager_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

  # prepared_statements: false


# run prod locally: RAILS_ENV=production rails c
