development:
  adapter: postgresql
  encoding: unicode
  database: volunteermanager
  host: localhost
  pool: 5
  username: christopher
  password: othello1

test:
  adapter: postgresql
  encoding: unicode
  database: volunteermanager
  host: localhost
  pool: 5myapp_dev
  username: christopher
  password: othello1
