default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host:    localhost
  port:     5433
  username: volunteer_user
  password: secure_password

development:
  <<: *default
  database: volunteer_manager_development

test:
  <<: *default
  database: volunteer_manager_test
